### ISSUE TITLE
fix BG button

### ISSUE THREAD

**Issue by Artur91425** [0ldi/ChatBar#1]
This fix for display of the BG button only on battlegrounds

ChatBar.lua
edit 274 line: 
return (GetZoneText() == CHATBAR_WSG or GetZoneText() == CHATBAR_AB or GetZoneText() == CHATBAR_AV) and (not ChatBar_HiddenButtons[CHAT_MSG_BATTLEGROUND]);

and add in locale files:
de:
CHATBAR_WSG = "Warsongschlucht";
CHATBAR_AB = "Arathibecken";
CHATBAR_AV = "Alteractal";
fr:
CHATBAR_WSG = "Goulet des Warsong";
CHATBAR_AB = "Bassin d'Arathi";
CHATBAR_AV = "Vall\195\169e d'Alterac";
en:
CHATBAR_WSG = "Warsong Gulch";
CHATBAR_AB = "Arathi Basin";
CHATBAR_AV = "Alterac Valley";

Add please ruRU:
[Localization.ru.zip](https://github.com/0ldi/ChatBar/files/863226/Localization.ru.zip)

**Comment by 0ldi** [comment]
done
