### ISSUE TITLE
Update please. I backported many enhancements from 2.4.3 - 5.4.8 versions...

### ISSUE THREAD

**Issue by Artur91425** [0ldi/ChatBar#2]
[ChatBar.zip](https://github.com/0ldi/ChatBar/files/917753/ChatBar.zip)
I backported several functions:
Added missing localizations
Added "Large Button" function
![bandicam 2017-04-12 23-11-51-292](https://cloud.githubusercontent.com/assets/24303693/24977620/51519f34-1fd6-11e7-8648-0cf6b0e4667a.jpg)
Added skin Squares
![bandicam 2017-04-12 23-12-16-290](https://cloud.githubusercontent.com/assets/24303693/24977644/63f05180-1fd6-11e7-8d9e-ed72b8bdc6e6.jpg)
Added "Hide all" functions
![bandicam 2017-04-12 23-11-36-135](https://cloud.githubusercontent.com/assets/24303693/24977772/dea00312-1fd6-11e7-8b5f-15c178f12bef.jpg)
and more...

All my backported changelog:
v.2.5
-Added larger buttons option to options menu
v2.4
-Added Simplified Chinese Localization (thanks IceChen)
-Added new Squares skin (thanks Chianti/Кьянти)
-Added new skin dropdown (Solid, Squares)
v2.3
-Added Traditional Chinese Localization
-Fixed a bug with Russian Localization
v2.2
-Removed SeaPrint usage
-Made Chronos optional: Reorder Channels is disabled w/o Chronos installed.
v2.1
-Added Russian Localization (thanks Старостин Алексей)
v2.0
-Added Alternate Artwork (thanks Zseton)
v1.9
-Added Spanish Localization (thanks NeKRoMaNT)
v1.8
-Added an option to Hide All Buttons
-Fixed menu not showing a list of hidden buttons

**Comment by 0ldi** [comment]
-squares mode flashing not work
-and i like this channel order:

> W - whisper
> S - say
> Y - yell
> E - emote
> P - party
> R - raid
> A - raidwarning
> B - battleground
> G - guild
> O - officer
> 1-10

I do not have time to fix this, so I'm waiting for your fix

**Comment by Artur91425** [comment]
xm...
Flashing works. Maybe you did not notice. Check again.
Corrected the order of the buttons.
[ChatBar.zip](https://github.com/0ldi/ChatBar/files/922817/ChatBar.zip)

**Comment by 0ldi** [comment]
hmm really flashing works, but it looks less noticeable.
omg i fck my brain how to rename\delete folder with browser github tool and not figured it out. So i install Github Desktop...
